name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}
  API_KEY: ${{ secrets.your-api-key }}

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: scan code for vulnerabilities
        run: |
          echo Downloading cdefense CLI
          curl https://raw.githubusercontent.com/kaushik94/cdefense-delta/blob/main/cd-latest-linux-x64 > /usr/local/bin/cdefense && chmod +x /usr/local/bin/cdefense
          cdefense online --api-key=b8ba2b0d-db93-4805-a916-65a469a7329d --repository-url="$REPO_URL" --pr-id="$GITHUB_PR_NUMBER"