name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}
  API_KEY: ${{ secrets.your-api-key }}

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: scan code for vulnerabilities
        run: |
          echo Downloading cdefense CLI
          export SCAN_URL=https://cc12-62-122-202-204.ngrok-free.app
          curl https://raw.githubusercontent.com/kaushik94/cdefense-delta/main/cdefense.tar.gz > /tmp/cdefense.tar.gz && tar -C /usr/local/bin -xzf /tmp/cdefense.tar.gz && chmod +x /usr/local/bin/cdefense
          cdefense online --api-key=32762768-54f7-4a53-af05-5bc7835bf9a2 --repository-url="$REPO_URL" --pr-id="$GITHUB_PR_NUMBER" --type=GITHUB